;;; -*- lexical-binding: t -*-
(setq max-lisp-eval-depth 100000)
(defun out (x) (princ (format "%s\n" x)))
(setq gc-cons-threshold 8000000)
(defun make-tree (d) (if (= d 0) (cons nil nil) (cons (make-tree (- d 1)) (make-tree (- d 1)))))
(defun check-tree (tr) (if (car tr) (+ 1 (check-tree (car tr)) (check-tree (cdr tr))) 1))
(defun bt-main ()
  (let ((maxd 16))
    (out (check-tree (make-tree (+ maxd 1))))
    (let ((long (make-tree maxd)) (d 4))
      (while (<= d maxd)
        (let ((iters (expt 2 (+ (- maxd d) 4))) (i 0) (sum 0))
          (while (< i iters) (setq sum (+ sum (check-tree (make-tree d)))) (setq i (1+ i)))
          (out sum))
        (setq d (+ d 2)))
      (out (check-tree long)))))
(bt-main)
