;;; -*- lexical-binding: t -*-
(setq max-lisp-eval-depth 100000)
(defun out (x) (princ (format "%s\n" x)))
(defun my-map (f l) (let ((acc nil)) (while l (push (funcall f (car l)) acc) (setq l (cdr l))) (nreverse acc)))
(defun my-filter (p l) (let ((acc nil)) (while l (when (funcall p (car l)) (push (car l) acc)) (setq l (cdr l))) (nreverse acc)))
(defun my-fold (f init l) (let ((acc init)) (while l (setq acc (funcall f acc (car l))) (setq l (cdr l))) acc))
(defun hof-main ()
  (let ((xs (number-sequence 0 199999)) (total 0))
    (dotimes (i 10)
      (let ((k (- 10 i)))
        (setq total (+ total (my-fold #'+ 0 (my-filter (lambda (x) (= 0 (% x 3)))
                                                       (my-map (lambda (x) (+ (* x x) k)) xs)))))))
    (out total)))
(hof-main)
