;;; -*- lexical-binding: t -*-
(setq max-lisp-eval-depth 100000)
(defun out (x) (princ (format "%s\n" x)))
(defun m-iter (cr ci mx)
  (let ((zr 0.0) (zi 0.0) (i 0))
    (while (and (/= i mx) (<= (+ (* zr zr) (* zi zi)) 4.0))
      (let ((nzr (+ (- (* zr zr) (* zi zi)) cr))) (setq zi (+ (* 2.0 zr zi) ci)) (setq zr nzr))
      (setq i (1+ i)))
    i))
(defun m-main ()
  (let ((size 250) (acc 0))
    (dotimes (y size) (dotimes (x size)
      (setq acc (+ acc (m-iter (- (* 3.0 (/ (float x) size)) 2.0) (- (* 2.0 (/ (float y) size)) 1.0) 200)))))
    (out acc)))
(m-main)
