;;; -*- lexical-binding: t -*-
(setq max-lisp-eval-depth 100000)
(defun out (x) (princ (format "%s\n" x)))
(defun org-lines (f) (with-temp-buffer (insert-file-contents f) (split-string (buffer-string) "\n" t)))
(defun o-prefix-p (line p) (string-prefix-p p line))
(defun o-main ()
  (let ((tags (make-hash-table :test 'equal)) (levels (make-vector 8 0)) (todos 0) (opn 0) (done 0) (words 0))
    (dolist (line (org-lines "org-sample.org"))
      (let* ((len (length line)) (stars 0))
        (while (and (< stars len) (eq (aref line stars) ?*)) (setq stars (1+ stars)))
        (cond
         ((and (> stars 0) (< stars 8) (< stars len) (eq (aref line stars) ?\s))
          (aset levels stars (1+ (aref levels stars)))
          (when (o-prefix-p (substring line (1+ stars)) "TODO ") (setq todos (1+ todos)))
          (when (and (> len 0) (eq (aref line (1- len)) ?:))
            (let ((i (1- len)))
              (while (and (>= i 0) (not (eq (aref line i) ?\s))) (setq i (1- i)))
              (when (>= i 0)
                (let ((start (+ i 2)) (j (+ i 2)))
                  (while (< j len)
                    (when (eq (aref line j) ?:)
                      (when (> j start) (let ((tag (substring line start j))) (puthash tag (1+ (gethash tag tags 0)) tags)))
                      (setq start (1+ j)))
                    (setq j (1+ j))))))))
         ((o-prefix-p line "- [ ] ") (setq opn (1+ opn)))
         ((o-prefix-p line "- [X] ") (setq done (1+ done)))
         (t (let ((i 0) (inw nil))
              (while (< i len)
                (let ((sp (eq (aref line i) ?\s)))
                  (when (and (not sp) (not inw)) (setq words (1+ words)))
                  (setq inw (not sp)))
                (setq i (1+ i))))))))
    (out (aref levels 1)) (out (aref levels 2)) (out (aref levels 3)) (out todos) (out opn) (out done) (out words)
    (out (hash-table-count tags)) (out (gethash "work" tags 0))))
(o-main)
