;;; -*- lexical-binding: t -*-
(setq max-lisp-eval-depth 100000)
(defun out (x) (princ (format "%s\n" x)))
(defvar qv)
(defun q-partition (lo hi)
  (let* ((v qv) (pivot (aref v hi)) (i lo) (j lo))
    (while (< j hi)
      (when (< (aref v j) pivot)
        (let ((tmp (aref v i))) (aset v i (aref v j)) (aset v j tmp)) (setq i (1+ i)))
      (setq j (1+ j)))
    (let ((tmp (aref v i))) (aset v i (aref v hi)) (aset v hi tmp))
    i))
(defun q-sort (lo hi) (when (< lo hi) (let ((p (q-partition lo hi))) (q-sort lo (1- p)) (q-sort (1+ p) hi))))
(defun qs-main ()
  (let* ((n 300000) (seed 42) (i 0))
    (setq qv (make-vector n 0))
    (while (< i n) (aset qv i seed) (setq seed (% (+ (* seed 75) 74) 65537)) (setq i (1+ i)))
    (q-sort 0 (1- n))
    (let ((ok t)) (dotimes (k (1- n)) (when (> (aref qv k) (aref qv (1+ k))) (setq ok nil)))
      (out (if ok "#t" "#f")))
    (out (aref qv 0)) (out (aref qv (/ n 2))) (out (aref qv (1- n)))))
(qs-main)
