[package]
name = "techne-vm"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
steel-parser = { path = "../steel-parser" }
rustc-hash = "2"
ctrlc = "3.5"
cranelift-codegen = "0.134"
cranelift-frontend = "0.134"
cranelift-jit = "0.134"
cranelift-module = "0.134"
cranelift-native = "0.134"
rustyline = { version = "15", default-features = false, features = ["with-file-history"] }
