;; Allocation/GC stress: short-lived and one long-lived binary tree.
(define (make d) (if (= d 0) (cons #f #f) (cons (make (- d 1)) (make (- d 1)))))
(define (check t) (if (car t) (+ 1 (check (car t)) (check (cdr t))) 1))
(define max-depth 16)
(out (check (make (+ max-depth 1))))
(define long-lived (make max-depth))
(define (iterate d)
  (when (<= d max-depth)
    (let ((iters (expt 2 (+ (- max-depth d) 4))))
      (let loop ((i 0) (sum 0))
        (if (< i iters) (loop (+ i 1) (+ sum (check (make d))))
            (out sum))))
    (iterate (+ d 2))))
(iterate 4)
(out (check long-lived))
