;; List construction, append and short-circuit recursion.
(define (iota1 n) (let loop ((i n) (l '())) (if (= i 0) l (loop (- i 1) (cons i l)))))
(define (ok? row dist placed)
  (if (null? placed) #t
      (and (not (= (car placed) (+ row dist)))
           (not (= (car placed) (- row dist)))
           (ok? row (+ dist 1) (cdr placed)))))
(define (try x y z)
  (if (null? x)
      (if (null? y) 1 0)
      (+ (if (ok? (car x) 1 z) (try (append (cdr x) y) '() (cons (car x) z)) 0)
         (try (cdr x) (cons (car x) y) z))))
(define (queens n) (try (iota1 n) '() '()))
(define (repeat n acc) (if (= n 0) acc (repeat (- n 1) (+ acc (queens 10)))))
(out (repeat 10 0))
