;; Org-like parsing: headings, TODO keywords, tags, checkboxes, words.
;; Works per line, using only string-ref/substring/char comparisons.
(define lines (file->lines "org-sample.org"))
(define tags (ht-new))
(define levels (make-vector 8 0))
(define todos 0)
(define open-boxes 0)
(define done-boxes 0)
(define words 0)
(define (prefix? line p)
  (let ((n (string-length p)))
    (and (>= (string-length line) n) (string=? (substring line 0 n) p))))
(define (count-stars line)
  (let ((len (string-length line)))
    (let loop ((i 0)) (if (and (< i len) (char=? (string-ref line i) #\*)) (loop (+ i 1)) i))))
(define (add-tags! line)
  ;; Trailing ":a:b:" segment after the last space.
  (let ((len (string-length line)))
    (when (and (> len 0) (char=? (string-ref line (- len 1)) #\:))
      (let find ((i (- len 1)))
        (cond ((< i 0) #f)
              ((char=? (string-ref line i) #\space)
               (let split ((start (+ i 2)) (j (+ i 2)))
                 (when (< j len)
                   (if (char=? (string-ref line j) #\:)
                       (begin
                         (when (> j start)
                           (let ((tag (substring line start j)))
                             (ht-set! tags tag (+ 1 (ht-ref tags tag 0)))))
                         (split (+ j 1) (+ j 1)))
                       (split start (+ j 1))))))
              (else (find (- i 1))))))))
(define (count-words line)
  (let ((len (string-length line)))
    (let loop ((i 0) (in-word #f) (n 0))
      (if (= i len) n
          (let ((space (char=? (string-ref line i) #\space)))
            (loop (+ i 1) (not space) (if (and (not space) (not in-word)) (+ n 1) n)))))))
(define (parse line)
  (let ((stars (count-stars line)))
    (cond ((and (> stars 0) (< stars 8) (< stars (string-length line))
                (char=? (string-ref line stars) #\space))
           (vector-set! levels stars (+ 1 (vector-ref levels stars)))
           (when (prefix? (substring line (+ stars 1) (string-length line)) "TODO ")
             (set! todos (+ todos 1)))
           (add-tags! line))
          ((prefix? line "- [ ] ") (set! open-boxes (+ open-boxes 1)))
          ((prefix? line "- [X] ") (set! done-boxes (+ done-boxes 1)))
          (else (set! words (+ words (count-words line)))))))
(define (each l) (when (not (null? l)) (parse (car l)) (each (cdr l))))
(each lines)
(out (vector-ref levels 1))
(out (vector-ref levels 2))
(out (vector-ref levels 3))
(out todos)
(out open-boxes)
(out done-boxes)
(out words)
(out (ht-count tags))
(out (ht-ref tags "work" 0))
