;; Vector access/mutation: in-place quicksort of pseudo-random integers.
(define n 300000)
(define v (make-vector n 0))
(let loop ((i 0) (seed 42))
  (when (< i n)
    (vector-set! v i seed)
    (loop (+ i 1) (modulo (+ (* seed 75) 74) 65537))))
(define (swap! i j) (let ((t (vector-ref v i))) (vector-set! v i (vector-ref v j)) (vector-set! v j t)))
(define (partition lo hi)
  (let ((pivot (vector-ref v hi)))
    (let loop ((i lo) (j lo))
      (if (< j hi)
          (if (< (vector-ref v j) pivot)
              (begin (swap! i j) (loop (+ i 1) (+ j 1)))
              (loop i (+ j 1)))
          (begin (swap! i hi) i)))))
(define (qsort lo hi)
  (when (< lo hi)
    (let ((p (partition lo hi)))
      (qsort lo (- p 1))
      (qsort (+ p 1) hi))))
(qsort 0 (- n 1))
(define (sorted? i) (or (>= i (- n 1)) (and (<= (vector-ref v i) (vector-ref v (+ i 1))) (sorted? (+ i 1)))))
(out (sorted? 0))
(out (vector-ref v 0))
(out (vector-ref v (quotient n 2)))
(out (vector-ref v (- n 1)))
