(define (out x) (display x) (newline))
(define (ht-new) (make-hashtable equal-hash equal?))
(define (ht-ref h k d) (hashtable-ref h k d))
(define (ht-set! h k v) (hashtable-set! h k v))
(define (ht-count h) (hashtable-size h))
(define (file->lines path)
  (let ((p (open-input-file path)))
    (let loop ((acc '()))
      (let ((l (get-line p)))
        (if (eof-object? l) (reverse acc) (loop (cons l acc)))))))
