(use-modules (ice-9 rdelim))
(define (out x) (display x) (newline))
(define (ht-new) (make-hash-table))
(define (ht-ref h k d) (hash-ref h k d))
(define (ht-set! h k v) (hash-set! h k v))
(define (ht-count h) (hash-count (const #t) h))
(define (file->lines path)
  (let ((p (open-input-file path)))
    (let loop ((acc '()))
      (let ((l (read-line p)))
        (if (eof-object? l) (reverse acc) (loop (cons l acc)))))))
