;; Elements move between two old vectors, through registers and through
;; fresh wrappers, while collections run; the keys must survive intact.
(define n 200)
(define u (make-vector n #f))
(define v (make-vector n #f))
(let loop ((i 0))
  (when (< i n)
    (vector-set! u i (cons i (* i i)))
    (vector-set! v i (cons (+ n i) (* (+ n i) (+ n i))))
    (loop (+ i 1))))
(define (unwrap e) (if (eq? (car e) 'w) (unwrap (cadr e)) e))
(define (valid? e) (let ((p (unwrap e))) (= (cdr p) (* (car p) (car p)))))
(define (key e) (car (unwrap e)))
(define (total)
  (let loop ((i 0) (s 0))
    (if (= i n) s (loop (+ i 1) (+ s (key (vector-ref u i)) (key (vector-ref v i)))))))
(define (all-valid?)
  (let loop ((i 0))
    (or (= i n) (and (valid? (vector-ref u i)) (valid? (vector-ref v i)) (loop (+ i 1))))))
(define expected (total))
(define seed 1)
(define (rand k) (set! seed (modulo (+ (* seed 1103515245) 12345) 2147483648)) (modulo (quotient seed 65536) k))
(define (garbage k) (let loop ((i 0) (l '())) (if (< i k) (loop (+ i 1) (cons i l)) (length l))))
(define (step)
  (let ((i (rand n)) (j (rand n)))
    (case (if (= 0 (rand 25)) 3 (rand 3))
      ;; Swap between the vectors.
      ((0) (let ((a (vector-ref u i)) (b (vector-ref v j)))
             (vector-set! u i b) (vector-set! v j a)))
      ;; Only a register holds the element for a while.
      ((1) (let ((a (vector-ref u i)))
             (vector-set! u i #f)
             (garbage 8)
             (vector-set! u i a)))
;; Registers hold elements across whole collection cycles.
      ((3) (let ((a (vector-ref u i)) (b (vector-ref v j)))
             (vector-set! u i #f) (vector-set! v j #f)
             (garbage 300)
             (vector-set! u i a) (vector-set! v j b)))
      ;; Swap through fresh wrappers.
      (else (let ((a (vector-ref u i)) (b (vector-ref v j)))
              (vector-set! u i (list 'w (unwrap b)))
              (vector-set! v j (list 'w (unwrap a))))))
    (garbage 2)))
(define (run k)
  (let loop ((k k) (bad 0))
    (if (= k 0)
        bad
        (begin (step) (loop (- k 1) (if (and (= 0 (modulo k 100)) (not (and (all-valid?) (= (total) expected)))) (+ bad 1) bad))))))
(displayln (list (run 3000) (= (total) expected) (all-valid?)))
